index:
    path: /
    controller: App\Controller\HomeController::index
    #Cette route est la route principale la page d'accueil du site
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout